from django.urls import path,include
from . import views

urlpatterns = [
    path('',views.login,name='login'),
    path('adminhome',views.adminhome,name='adminhome'),
    path('userregister',views.userregister,name='userregister'),
    path('home',views.home,name='home'),
    path('adminuserview',views.adminuserview,name='adminuserview'),
    path('userdelete/<int:id>/',views.userdelete,name='userdelete'),
    path('userblock/<int:id>/',views.userblock,name='userblock'),
    path('userunblock/<int:id>/',views.userunblock,name='userunblock'),
    path('post_create',views.post_create,name='post_create'),
    path('mypost',views.mypost,name='mypost'),
    path('adminpostview',views.adminpostview,name='adminpostview'),
    path('admindltpost/<int:id>',views.admindltpost,name='admindltpost'),
    path('mypostdlt/<int:id>',views.mypostdlt,name='mypostdlt'),
    path('logout',views.logout,name='logout'),
    path('comment/<int:id>',views.comment,name='comment'),
    path('usercmtview/<int:id>', views.usercmtview, name='usercmtview'),
    path('mypostedit/<int:id>', views.mypostedit, name='mypostedit'),
    path('like/<int:id>',views.like,name='like'),
    path('reel_like/<int:id>',views.reel_like,name='reel_like'),
    path('mylikeview/<int:id>',views.mylikeview,name='mylikeview'),
    path('reel_like_view/<int:id>',views.reel_like_view,name='reel_like_view'),
    path('view_other_users',views.view_other_users,name='view_other_users'),
    path('followrequest/<int:id>',views.followrequest,name='followrequest'),
    path('follow',views.follow,name='follow'),
    path('followback/<int:id>',views.followback,name='followback'),
    path('myfollowers',views.myfollowers,name='myfollowers'),
    path('reel_create',views.reel_create,name='reel_create'),
    path('reel_view',views.reel_view,name='reel_view'),
    path('adminreelview',views.adminreelview,name='adminreelview'),
    path('reel_cmt/<int:id>',views.reel_cmt,name='reel_cmt'),
    path('reelcmtview/<int:id>',views.reelcmtview,name='reelcmtview'),
    path('reeledit/<int:id>',views.reeledit,name='reeledit'),
    path('reeldlt/<int:id>',views.reeldlt,name='reeldlt'),
    path('usermsgview',views.usermsgview,name='usermsgview'),
    path('sendmessage/<int:receiver_id>',views.sendmessage,name='sendmessage'),
    path('adminmsgview',views.adminmsgview,name='adminmsgview'),
]