# Generated by Django 3.2.25 on 2025-10-08 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='LOGIN',
            new_name='USER',
        ),
    ]
