# Generated by Django 3.2.25 on 2025-10-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='count',
            field=models.IntegerField(),
        ),
    ]
