# Generated by Django 3.2.25 on 2025-10-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_post_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='count',
            field=models.IntegerField(max_length=1000),
        ),
    ]
