# Generated by Django 3.2.25 on 2025-10-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_likes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='count',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
