# Generated by Django 3.2.25 on 2025-10-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_likes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='count',
            field=models.IntegerField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
