# Generated by Django 3.2.25 on 2025-10-10 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_likes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='count',
        ),
    ]
