# Generated by Django 3.2.25 on 2025-10-10 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_likes_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('USER_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='myapp.user')),
                ('USER_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='myapp.user')),
            ],
        ),
    ]
