# Generated by Django 5.2.7 on 2025-10-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_reel'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
