# Generated by Django 5.2.7 on 2025-10-18 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_reel_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='REEL',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.reel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reel',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
