# Generated by Django 5.2.7 on 2025-10-18 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_likes_reel_reel_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='date_time',
        ),
    ]
