# Generated by Django 5.2.7 on 2025-10-18 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_likes_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='REEL',
        ),
        migrations.CreateModel(
            name='Rlike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REEL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.reel')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
