# Generated by Django 5.2.7 on 2025-10-18 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_likes_reel_rlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rcomment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('REEL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.reel')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
