# Generated by Django 5.2.7 on 2025-10-22 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_message_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='USER',
        ),
        migrations.AddField(
            model_name='message',
            name='Reciever',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='myapp.user'),
        ),
        migrations.AddField(
            model_name='message',
            name='Sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='myapp.user'),
        ),
    ]
